'use strict';
// To append another language copy and paste the enUs as a template, substitute the terms were you feel apropriate and append the language code to the languages const.
// import {findName} from ./language.js
const enUS = {
  locale: 'en-US',
  Meshes: 'Meshes',
  Files: 'Files',
  Materials: 'Materials',
  Details: 'Details',
  Configurations: 'Configurations',
  Scope: 'Scope',
  EntireModel: 'Entire Model',
  VisibleOnly: 'Visible Only',
  Rotation: 'Rotation',
  NoRotation: 'No Rotation',
  NinDegM: '-90 Degrees',
  NinDegP: '90 Degrees',
  ExportFailed: 'Export Failed',
  textExportFail: "The model doesn't contain any meshes.",
  ExportingModel: 'Exporting Model',
  textOBJ: 'Wavefront (.obj)',
  textSTL: 'Stereolithography Text (.stl)',
  textBSTL: 'Stereolithography Binary (.stl)',
  textPLY: 'Polygon File Format Text (.ply)',
  textBPLY: 'Polygon File Format Binary (.ply)',
  textGLTF: 'glTF Text (.gltf)',
  textBGLTF: 'glTF Binary (.glb)',
  textOFF: 'Object File Format Text (.off)',
  text3DM: 'Rhinoceros 3D (.3dm)',
  textBIM: 'Dotbim (.bim)',
  Export: 'Export',
  Close: 'Close',
  textExportW:
    'Select the format from the list below, and adjust the settings of the selected format.',
  SelectPoint: 'Select a point.',
  SelectAnotherPoint: 'Select another point.',
  DistanceOfPoints: 'Distance of points',
  DistanceOfParallelFaces: 'Distance of parallel faces',
  AngleOfFaces: 'Angle of faces',
  OpenUrl: 'Open from url',
  Cancel: 'Cancel',
  OK: 'OK',
  textOpenUrl:
    'Here you can load models based on their urls. You can add more lines if your model builds up from multiple files.',
  Copy: 'Copy',
  Copied: 'Copied',
  SharingLink: 'Sharing Link',
  EmbeddingCode: 'Embedding Code',
  CustomConfig: 'Use customized settings',
  SharingFailed: 'Sharing Failed',
  textShareFail:
    'Sharing works only if you load files by url. Please upload your model files to a web server, open them by url, and try embedding again.',
  Share: 'Share',
  Vertices: 'Vertices',
  Triangles: 'Triangles',
  Unit: 'Unit',
  SizeX: 'Size X',
  SizeY: 'Size Y',
  SizeZ: 'Size Z',
  Volume: 'Volume',
  Surface: 'Surface',
  MissingFiles: 'Missing files',
  AvailableFiles: 'Available files',
  FlatList: 'Flat list',
  TreeView: 'Tree view',
  ExpandAll: 'Expand all',
  CollapseAll: 'Collapse all',
  SHMeshes: 'Show/Hide meshes',
  FitMeshesToWindow: 'Fit meshes to window',
  Millimeter: 'Millimeter',
  Centimeter: 'Centimeter',
  Meter: 'Meter',
  Inch: 'Inch',
  Foot: 'Foot',
  Unknown: 'Unknown',
  Calculate: 'Calculate...',
  PleaseWait: 'Please wait...',
  ModelDisplay: 'Model display',
  BackgroundColor: 'Background color',
  BackgroundImage: 'Background image',
  Environment: 'Environment',
  ShowEdges: 'Show edges',
  EdgeColor: 'Edge color',
  EdgeAngleThreshold: 'Edge angle threshold',
  ImportSettings: 'Import settings',
  DefaultColor: 'Default color',
  ResetToDefault: 'Reset to default',
  Settings: 'Settings',
  Small: 'Small (1280x720)',
  Medium: 'Medium (1920x1080)',
  Large: 'Large (2560x1440)',
  Custom: 'Custom',
  CreateSnapshot: 'Create Snapshot',
  Create: 'Create',
  Width: 'Width',
  Height: 'Height',
  TransparentBackground: 'Transparent background',
  LoadingModel: 'Loading Model...',
  ImportingModel: 'Importing Model...',
  VisualizingModel: 'Visualizing Model...',
  SomethingWentWrong: 'Something went wrong.',
  NoImportableFileFound: 'No importable file found.',
  FailedToLoadFileForImport: 'Failed to load file for import.',
  textFailLoadImport:
    'The remote server refused to fulfill the request. Check if the url is correct, and make sure that CORS requests are allowed on the remote server.',
  FailedToImportModel: 'Failed to import model.',
  UnknownError: 'Unknown error.',
  SelectModel: 'Select Model',
  textMultipleFilesFound:
    'Multiple importable models found. Select the model you would like to import from the list below.',
  NoName: 'No name',
  FitModelToWindow: 'Fit model to window',
  ShowAllMeshes: 'Show all meshes',
  HideMesh: 'Hide mesh',
  FitMeshToWindow: 'Fit mesh to window',
  RemoveIsolation: 'Remove isolation',
  IsolateMesh: 'Isolate mesh',
  OpenFromYourDevice: 'Open from your device',
  OpenFromUrl: 'Open from url',
  SetYAxis: 'Set Y axis as up vector',
  SetZAxis: 'Set Z axis as up vector',
  FlipUpVector: 'Flip up vector',
  FixedUpVector: 'Fixed up vector',
  FreeOrbit: 'Free orbit',
  PerspectiveCamera: 'Perspective camera',
  OrthographicCamera: 'Orthographic camera',
  Measure: 'Measure',
  Download: 'Download',
  DarkMode: 'Dark mode',
  LightMode: 'Light mode',
  textCookie:
    'This website uses cookies to offer you better user experience. See the details at the <a target="_blank" href="info/cookies.html">Cookies Policy</a> page.',
  Accept: 'Accept',
};
const ptBR = {
  locale: 'pt-BR',
  Meshes: 'Malhas',
  Files: 'Arquivos',
  Materials: 'Materiais',
  Details: 'Detalhes',
  Configurations: 'Configurações',
  Scope: 'Escopo',
  EntireModel: 'Modelo inteiro',
  VisibleOnly: 'Só os visíveis',
  Rotation: 'Rotação',
  NoRotation: 'Sem Rotação',
  NinDegM: '-90 graus',
  NinDegP: '90 graus',
  ExportFailed: 'Falha na Exportação',
  textExportFail: "The model doesn't contain any meshes.",
  ExportingModel: 'Exportando Modelo',
  textOBJ: 'Wavefront (.obj)',
  textSTL: 'Stereolithography Texto (.stl)',
  textBSTL: 'Stereolithography Binário (.stl)',
  textPLY: 'Polygon File Format Texto (.ply)',
  textBPLY: 'Polygon File Format Binário (.ply)',
  textGLTF: 'glTF Texto (.gltf)',
  textBGLTF: 'glTF Binário (.glb)',
  textOFF: 'Object File Format Texto (.off)',
  text3DM: 'Rhinoceros 3D (.3dm)',
  textBIM: 'Dotbim (.bim)',
  Export: 'Exportar',
  Close: 'Fechar',
  textExportW:
    'Selecione o formato da lista abaixo e ajuste suas respectivas configurações.',
  SelectPoint: 'Selecione um ponto.',
  SelectAnotherPoint: 'Selecione outro ponto.',
  DistanceOfPoints: 'Distância entre pontos',
  DistanceOfParallelFaces: 'Distância entre faces paralelas',
  AngleOfFaces: 'Ângulo entre as faces',
  OpenUrl: 'Abrir de endereço online',
  Cancel: 'Cancelar',
  OK: 'OK',
  textOpenUrl:
    'Aqui você pode carregar modelos baseado em urls. Você pode adicionar mais linhas se o modelo requerer arquivos múltiplos.',
  Copy: 'Copiar',
  Copied: 'Copiado',
  SharingLink: 'Link de compartilhamento',
  EmbeddingCode: 'Código incorporado',
  CustomConfig: 'Usar configurações personalizadas',
  SharingFailed: 'Compartilhamento falhou',
  textShareFail:
    'O compartilhamento só funciona se você carregar os arquivos por uma url. Por favor suba seus arquivos de modelo para um servidor web, abra-os pela url e tente incorporá-los de novo.',
  Share: 'Compartilhar',
  Vertices: 'Vértices',
  Triangles: 'Triângulos',
  Unit: 'Unidade',
  SizeX: 'Tamanho X',
  SizeY: 'Tamanho Y',
  SizeZ: 'Tamanho Z',
  Volume: 'Volume',
  Surface: 'Superfície',
  MissingFiles: 'Arquivos faltantes',
  AvailableFiles: 'Arquivos disponíveis',
  FlatList: 'Lista',
  TreeView: 'Visão em árvore',
  ExpandAll: 'Expandir tudo',
  CollapseAll: 'Colapsar tudo',
  SHMeshes: 'Mostrar/Ocultar malhas',
  FitMeshesToWindow: 'Encaixar malha na janela',
  Millimeter: 'Milímetro',
  Centimeter: 'Centímetro',
  Meter: 'Metro',
  Inch: 'Polegada',
  Foot: 'Pé',
  Unknown: 'Desconhecido',
  Calculate: 'Calculando...',
  PleaseWait: 'Espere por favor...',
  ModelDisplay: 'Exibição do Modelo',
  BackgroundColor: 'Cor de fundo',
  BackgroundImage: 'Imagem de fundo',
  Environment: 'Ambiente',
  ShowEdges: 'Mostrar arestas',
  EdgeColor: 'Cor da aresta',
  EdgeAngleThreshold: 'Limite angular da aresta',
  ImportSettings: 'Ajustes de Importação',
  DefaultColor: 'Cor padrão',
  ResetToDefault: 'Retornar às configurações originais',
  Settings: 'Ajustes',
  Small: 'Pequeno (1280x720)',
  Medium: 'Médio (1920x1080)',
  Large: 'Grande (2560x1440)',
  Custom: 'Personalizado',
  CreateSnapshot: 'Criar foto',
  Create: 'Criar',
  Width: 'Largura',
  Height: 'Altura',
  TransparentBackground: 'Fundo transparente',
  LoadingModel: 'Carregando Modelo',
  ImportingModel: 'Importando Modelo',
  VisualizingModel: 'Visualizando Modelo',
  SomethingWentWrong: 'Algo deu errado.',
  NoImportableFileFound: 'Nenhum arquivo importável encontrado.',
  FailedToLoadFileForImport: 'Falha no carregamento do arquivo importado.',
  textFailLoadImport:
    'O servidor remoto recusou o pedido. Confira se a url está correta e assegure-se que o servidor remoto aceita pedidos CORS.',
  FailedToImportModel: 'Falha na importação do modelo.',
  UnknownError: 'Erro desconhecido.',
  SelectModel: 'Selecione o Modelo',
  textMultipleFilesFound:
    'Vários arquivos importáveis encontrados. Selecione o modelo que você deseja importar da lista abaixo.',
  NoName: 'Nenhum nome',
  FitModelToWindow: 'Encaixar modelo na janela',
  ShowAllMeshes: 'Mostrar todas as malhas',
  HideMesh: 'Ocultar malha',
  FitMeshToWindow: 'Encaixar malha na janela',
  RemoveIsolation: 'Remover isolamento',
  IsolateMesh: 'Isolar malha',
  OpenFromYourDevice: 'Abrir do próprio dispositivo',
  OpenFromUrl: 'Abrir de uma url',
  SetYAxis: 'Definir eixo Y como vetor vertical',
  SetZAxis: 'Definir eixo z como vetor vertical',
  FlipUpVector: 'Inverter vetor',
  FixedUpVector: 'Fixar vetor vertical',
  FreeOrbit: 'Órbita livre',
  PerspectiveCamera: 'Câmera em Perspectiva',
  OrthographicCamera: 'Câmera Ortográfica',
  Measure: 'Medir',
  Download: 'Download',
  DarkMode: 'Modo escuro',
  LightMode: 'Modo claro',
  textCookie:
    'Este website usa cookies para oferecer uma melhor experiência de navegação. Veja os detalhes na página <a target="_blank" href="info/cookies.html">Política de Cookies</a>.',
  Accept: 'Aceitar',
};

const languages = [enUS, ptBR];
export function findName(name) {
  if (
    languages.find((lang) => lang.locale === navigator.language && lang[name])
  ) {
    return languages.find((lang) => lang.locale === navigator.language)[name];
  } else {
    return languages.find((lang) => lang.locale === 'en-US')[name];
  }
}
